### ISSUE TITLE
fix spacing on privacy page

### ISSUE THREAD

**Issue by weddleben** [LadyBluenotes/track-my-funds#5]
My [last PR](https://github.com/LadyBluenotes/track-my-funds/pull/3) fixed the broken link, but caused a spacing issue.

![ss](https://user-images.githubusercontent.com/107364642/228652301-7f2c5437-b8e6-4310-b7fe-3563d96767d2.PNG)

Sorry! I don't know React and didn't test before submitting.

**Comment by LadyBluenotes** [comment]
Thank you for checking it out! I didn't do a thorough enough check to see how it would look upon being pushed to the repo.
